name: Test 

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Tests
      env:
        BUILDING_MODE: dev
        PYTHONPATH: ../../..
      run: |
        pipenv run coverage run --source=. -m pytest
        pipenv run coverage report -m --omit="*/tests/*"
 
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}