name: Test 

on: push [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Tests
      run: |
        pipenv run coverage run --source=. -m pytest && pipenv run coverage xml
        pipenv run coverage report -m --omit="*/tests/*"
 
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)